name: MacOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Gluon Build
        run: mvn -Pdesktop client:build client:package

      - name: Copy native client to staging
        run: cp -r target/client/x86_64-darwin/HelloGluon* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

